---
abstract: 'Routines useful for processing network abuse'
author:
  - 'Michael Greb <mgreb@linode.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Abuse-Utils
no_index:
  directory:
    - t
    - inc
requires:
  Email::Address: 0
  Net::DNS: 0
  Net::Whois::IP: 0
  perl: 5.006
version: 0.11_01
