--- #YAML:1.0
name:               Net-Abuse-Utils
version:            0.11
abstract:           Routines useful for processing network abuse
author:
    - Michael Greb <mgreb@linode.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Email::Address:  0
    Net::DNS:        0
    Net::Whois::IP:  0
    perl:            5.006
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
